/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.ControleAvaliar;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTextField;
import model.Filme;

/**
 *
 * @author lucas
 */
public class Avaliar extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Avaliar.class.getName());

    /**
     * Creates new form Avaliar
     */
    public Avaliar(Filme filme) {
        initComponents();
        ca = new ControleAvaliar(this, filme);
    }

    public JButton getjButton1() {
        return bt_enviar;
    }

    public void setjButton1(JButton jButton1) {
        this.bt_enviar = jButton1;
    }

    public JLabel getLbl_inisiraNota() {
        return lbl_inisiraNota;
    }

    public void setLbl_inisiraNota(JLabel lbl_inisiraNota) {
        this.lbl_inisiraNota = lbl_inisiraNota;
    }

    public JTextField getTxt_nota() {
        return txt_nota;
    }

    public void setTxt_nota(JTextField txt_nota) {
        this.txt_nota = txt_nota;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_inisiraNota = new javax.swing.JLabel();
        txt_nota = new javax.swing.JTextField();
        bt_enviar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lbl_inisiraNota.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbl_inisiraNota.setText("Insira a nota do filme:");

        txt_nota.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_nota.setText("(0 - 5)");
        txt_nota.addActionListener(this::txt_notaActionPerformed);

        bt_enviar.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        bt_enviar.setText("ENVIAR");
        bt_enviar.addActionListener(this::bt_enviarActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbl_inisiraNota, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txt_nota, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(bt_enviar, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbl_inisiraNota, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                    .addComponent(txt_nota))
                .addGap(28, 28, 28)
                .addComponent(bt_enviar, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_notaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_notaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_notaActionPerformed

    private void bt_enviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_enviarActionPerformed
            // TODO add your handling code here:
            ca.avaliar();
    }//GEN-LAST:event_bt_enviarActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
//            logger.log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(() -> new Avaliar().setVisible(true));
//    }

    private ControleAvaliar ca;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_enviar;
    private javax.swing.JLabel lbl_inisiraNota;
    private javax.swing.JTextField txt_nota;
    // End of variables declaration//GEN-END:variables
}
