/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.ControleCriarLista;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTextField;
import model.Usuario;

/**
 *
 * @author lucas
 */
public class CriarLista extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CriarLista.class.getName());

    /**
     * Creates new form CriarLista
     */
    public CriarLista(Usuario user) {
        initComponents();
        ccl = new ControleCriarLista(user, this);
    }

    public JButton getjButton1() {
        return bt_criar;
    }

    public void setjButton1(JButton jButton1) {
        this.bt_criar = jButton1;
    }

    public JButton getjButton2() {
        return jButton2;
    }

    public void setjButton2(JButton jButton2) {
        this.jButton2 = jButton2;
    }

    public JButton getjButton3() {
        return bt_cancelar;
    }

    public void setjButton3(JButton jButton3) {
        this.bt_cancelar = jButton3;
    }

    public JLabel getLbl_lista() {
        return lbl_lista;
    }

    public void setLbl_lista(JLabel lbl_lista) {
        this.lbl_lista = lbl_lista;
    }

    public JTextField getTxt_nomeLista() {
        return txt_nomeLista;
    }

    public void setTxt_nomeLista(JTextField txt_nomeLista) {
        this.txt_nomeLista = txt_nomeLista;
    }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        lbl_lista = new javax.swing.JLabel();
        txt_nomeLista = new javax.swing.JTextField();
        bt_criar = new javax.swing.JButton();
        bt_cancelar = new javax.swing.JButton();

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton2.setText("Criar");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Criar Lista");

        lbl_lista.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_lista.setText("Nome da Lista:");

        txt_nomeLista.addActionListener(this::txt_nomeListaActionPerformed);

        bt_criar.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        bt_criar.setText("Criar");
        bt_criar.addActionListener(this::bt_criarActionPerformed);

        bt_cancelar.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        bt_cancelar.setText("Cancelar");
        bt_cancelar.addActionListener(this::bt_cancelarActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lbl_lista)
                .addGap(18, 18, 18)
                .addComponent(txt_nomeLista, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(48, Short.MAX_VALUE)
                .addComponent(bt_criar, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(bt_cancelar)
                .addGap(50, 50, 50))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_lista, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_nomeLista, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_criar, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(79, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_criarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_criarActionPerformed
        // TODO add your handling code here:
        ccl.CriarLista();
    }//GEN-LAST:event_bt_criarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void bt_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_cancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_cancelarActionPerformed

    private void txt_nomeListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nomeListaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nomeListaActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
//            logger.log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(() -> new CriarLista().setVisible(true));
//    }

    private ControleCriarLista ccl;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_cancelar;
    private javax.swing.JButton bt_criar;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel lbl_lista;
    private javax.swing.JTextField txt_nomeLista;
    // End of variables declaration//GEN-END:variables
}
