/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.ControleAvaliar;
import controller.ControleReproducao;
import java.awt.Color;
import java.util.ArrayList;
import model.Filme;
import model.Usuario;

/**
 *
 * @author lucas
 */
public class Reproducao extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Reproducao.class.getName());

    /**
     * Creates new form Reproducao
     */
    public Reproducao(Filme filme, Usuario user, ArrayList<Filme> filmes) {
        initComponents();
        this.filmes = filmes;
        this.filme = filme;
        this.user = user;
        cr = new ControleReproducao(this, filme, user, filmes);
        
        posIniciar(filme, user);
    }

    private void posIniciar(Filme filme, Usuario user){
        lbl_titulo.setText(filme.getTitulo());
        lbl_descricao.setText("<html>" + filme.getDescricao() + "<br>");
        lbl_avaliacoes.setText("Avaliacoes: " + filme.getAvaliacoes() / filme.getnAvaliacoes());
        lbl_tempo.setText("0:0:0 / " + filme.getHoras() + ":" + filme.getMinutos() + ":" + filme.getSegundos());

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bt_favoritar1 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        lbl_titulo = new javax.swing.JLabel();
        bt_voltar = new javax.swing.JButton();
        bt_avaliar = new javax.swing.JButton();
        lbl_avaliacoes = new javax.swing.JLabel();
        lbl_descricao = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        bt_addListaDeReproducao = new javax.swing.JButton();
        bt_favoritar = new javax.swing.JButton();
        bt_pausar = new javax.swing.JButton();
        bt_voltarVideo = new javax.swing.JButton();
        bt_reiniciar = new javax.swing.JButton();
        bt_avancar = new javax.swing.JButton();
        lbl_tempo = new javax.swing.JLabel();

        bt_favoritar1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bt_favoritar1.setText("Favoritar");

        jButton5.setFont(new java.awt.Font("Segoe UI Emoji", 0, 24)); // NOI18N
        jButton5.setText("⏯️");
        jButton5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton5.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButton5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1080, 720));

        lbl_titulo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbl_titulo.setText("Nome Filme");

        bt_voltar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bt_voltar.setText("VOLTAR");
        bt_voltar.addActionListener(this::bt_voltarActionPerformed);

        bt_avaliar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bt_avaliar.setText("Avaliar");
        bt_avaliar.addActionListener(this::bt_avaliarActionPerformed);

        lbl_avaliacoes.setText("\"Avaliacoes: \" + filme.getAvaliacoes() / filme.getnAvaliacoes()");
        lbl_avaliacoes.setToolTipText("");

        lbl_descricao.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_descricao.setText("Descricao");
        lbl_descricao.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lbl_descricao.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        lbl_descricao.setOpaque(true);

        jLabel1.setBackground(new java.awt.Color(51, 51, 51));
        jLabel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jLabel1.setOpaque(true);

        bt_addListaDeReproducao.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bt_addListaDeReproducao.setText("Adicionar a lista de reproducao");
        bt_addListaDeReproducao.addActionListener(this::bt_addListaDeReproducaoActionPerformed);

        bt_favoritar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bt_favoritar.setText("Favoritar");
        bt_favoritar.addActionListener(this::bt_favoritarActionPerformed);

        bt_pausar.setFont(new java.awt.Font("Segoe UI Emoji", 0, 24)); // NOI18N
        bt_pausar.setText("⏯️");
        bt_pausar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bt_pausar.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        bt_pausar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        bt_voltarVideo.setFont(new java.awt.Font("Segoe UI Emoji", 0, 24)); // NOI18N
        bt_voltarVideo.setText("⏪");
        bt_voltarVideo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bt_voltarVideo.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        bt_voltarVideo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bt_voltarVideo.addActionListener(this::bt_voltarVideoActionPerformed);

        bt_reiniciar.setFont(new java.awt.Font("Segoe UI Emoji", 0, 24)); // NOI18N
        bt_reiniciar.setText("🔁");
        bt_reiniciar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bt_reiniciar.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        bt_reiniciar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        bt_avancar.setFont(new java.awt.Font("Segoe UI Emoji", 0, 24)); // NOI18N
        bt_avancar.setText("⏩");
        bt_avancar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bt_avancar.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        bt_avancar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bt_avancar.addActionListener(this::bt_avancarActionPerformed);

        lbl_tempo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_tempo.setText("TEMPO");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bt_voltar)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1000, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_descricao, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bt_favoritar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(bt_addListaDeReproducao, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(bt_pausar)
                                    .addGap(18, 18, 18)
                                    .addComponent(bt_reiniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(bt_voltarVideo, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(bt_avancar, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(lbl_tempo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(bt_avaliar, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(lbl_avaliacoes, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bt_voltar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 504, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(bt_pausar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lbl_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(bt_reiniciar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(bt_voltarVideo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(lbl_tempo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(bt_avancar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lbl_descricao, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bt_avaliar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_avaliacoes, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bt_favoritar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bt_addListaDeReproducao, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_voltarActionPerformed
        // TODO add your handling code here:
        Home h = new Home(user, filmes);
        h.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_bt_voltarActionPerformed

    private void bt_voltarVideoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_voltarVideoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_voltarVideoActionPerformed

    private void bt_avancarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_avancarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_avancarActionPerformed

    private void bt_favoritarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_favoritarActionPerformed
        cr.Adicionar();
    }//GEN-LAST:event_bt_favoritarActionPerformed

    private void bt_addListaDeReproducaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_addListaDeReproducaoActionPerformed
        // TODO add your handling code here:
        AdicionarLista al = new AdicionarLista(user.getEmail(), filme);
        al.setVisible(true);
    }//GEN-LAST:event_bt_addListaDeReproducaoActionPerformed

    private void bt_avaliarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_avaliarActionPerformed
        // TODO add your handling code here:
        Avaliar ca = new Avaliar(filme);
        ca.setVisible(true);
        
    }//GEN-LAST:event_bt_avaliarActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
//            logger.log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(() -> new Reproducao().setVisible(true));
//    }

    private Usuario user;
    private Filme filme;
    private ArrayList<Filme> filmes;
    private ControleReproducao cr;
    private Avaliar ca;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_addListaDeReproducao;
    private javax.swing.JButton bt_avaliar;
    private javax.swing.JButton bt_avancar;
    private javax.swing.JButton bt_favoritar;
    private javax.swing.JButton bt_favoritar1;
    private javax.swing.JButton bt_pausar;
    private javax.swing.JButton bt_reiniciar;
    private javax.swing.JButton bt_voltar;
    private javax.swing.JButton bt_voltarVideo;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbl_avaliacoes;
    private javax.swing.JLabel lbl_descricao;
    private javax.swing.JLabel lbl_tempo;
    private javax.swing.JLabel lbl_titulo;
    // End of variables declaration//GEN-END:variables
}
