/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.ControleAdicionarLista;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JLabel;
import model.Filme;

/**
 *
 * @author lucas
 */
public class AdicionarLista extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AdicionarLista.class.getName());

    /**
     * Creates new form AdicionarLista
     */
    public AdicionarLista(String email, Filme filme) {
        initComponents();
        this.email = email;
        this.filme = filme;
        cal = new ControleAdicionarLista(email, this);
        nomesListas = cal.setNomesListas();
        System.out.println(nomesListas);
        iniciar();
        
    }
    
    public void iniciar(){
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        String str;  
        
        for (int i = 0; i < nomesListas.size(); i++){
            lbl_opcao = new javax.swing.JLabel();
            str = nomesListas.get(i);
            criarOpcaoListas(nomesListas, lbl_opcao, layout, i);
        }
    }

    private void criarOpcaoListas(ArrayList<String> nomesListas,JLabel lbl_opcao, javax.swing.GroupLayout layout, int i){
        lbl_opcao.setFont(new java.awt.Font("Segoe UI", 1, 18));
        lbl_opcao.setText("<html>" + nomesListas.get(i) + "<br>");
        lbl_opcao.setOpaque(true);
        lbl_opcao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_opcao.setPreferredSize(new java.awt.Dimension(365, 25));
        lbl_opcao.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        
        lbl_opcao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_opcaoMouseClicked(evt, nomesListas.get(i), email);
            }
        });

        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(50,50,50)
                .addComponent(lbl_opcao, 300, 300, 300))
        );
        layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addGap(60 + i * 35, 60 + i * 35, 60 + i * 35)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(lbl_opcao, 30, 30, 30))
            .addContainerGap(0, Short.MAX_VALUE))
        );
        pack();          
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(420, 400));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Escolha a que lista deseja adicionar o filme");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(242, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lbl_opcaoMouseClicked(java.awt.event.MouseEvent evt, String nomeLista, String email) {                                            
        // TODO add your handling code here:
        String str = "tb" + email + nomeLista.replaceAll(" ", "_");
        System.out.println(str);
        cal.inserir(nomeLista, filme);

    }  
    
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
//            logger.log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(() -> new AdicionarLista().setVisible(true));
//    }

    private String email;
    private JLabel lbl_opcao;
    private ControleAdicionarLista cal;
    private ArrayList<String> nomesListas;
    private Filme filme;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
